### PR TITLE
Update to patch 9.6

### PR DESCRIPTION
**Pull request by 1337MARCEL**

### CODE REVIEW

**Comment by jjmaldonis** [comment]
Hey thanks for the commit. Usually we get one from Canisback.

Do you mind me asking how you calculated the patch start time?

**Comment by 1337MARCEL** [comment]
> Hey thanks for the commit. Usually we get one from Canisback.
> 
> Do you mind me asking how you calculated the patch start time?

1. Head over to https://www.epochconverter.com/
2. Get timestamp for **Wednesday, March 20, 2019 8:00:00 AM GMT**

**Comment by jjmaldonis** [comment]
Sure but how did you come up with the timestamp? There are a few different ways you can do it. I know how this all works so I'd like to know the method you used so we keep things consistent.

**Comment by 1337MARCEL** [comment]
I simply went back and checked what time @Canisback used.

**Comment by Canisback** [comment]
Sorry I need to fix my auto-PR thing, I did the PR from my repo just now.

**Comment by Morilli** [comment]
Your PR seems to have a different time tho

**Comment by 1337MARCEL** [comment]
Feel free to close my PR if the timestamp is incorrect 👍

**Comment by jjmaldonis** [comment]
Hey thank you for the PR though! If nothing else it pinged Canisback to update his script and now we have the updated data!

**Pull request closed without merging**
